### ISSUE TITLE
Please verify the router and factory contracts

### ISSUE THREAD

**Issue by helpfulBro** [trisolaris-labs/trisolaris_core#44]
Factory: 0xc66F594268041dB60507F00703b152492fb176E7
Router: 0x2CB45Edb4517d5947aFdE3BEAbF95A582506858B

On https://aurorascan.dev/

Thanks

**Comment by baboobhaiya** [comment]
@helpfulBro thanks for raising the issue:

Contracts deployed before 19th Oct 2021 or deployed via internal transactions are not identified as contracts via aurorascan but identified as EOA’s. This means that we cannot verify contracts which fall in the above two categories. We are in contact with Aurora and Etherscan teams to fix the issues by end of Q2. 

https://trisolaris-labs.github.io/docs/contracts/#decentralization-conract-verification

**Comment by helpfulBro** [comment]
Thanks for the quick response @baboobhaiya - would be great if you could post links to the ABIs on the docs until the contracts are verified, just to make it a bit easier for users/devs to interact with the contracts until resolved.

**Comment by baboobhaiya** [comment]
hey, you can build the abi's using the `trisolaris_core` repo: https://github.com/trisolaris-labs/trisolaris_core#compile

**Comment by helpfulBro** [comment]
Thanks 🙏
